### ISSUE TITLE
DefPartRenderer mouse event listener messing up focus

### ISSUE THREAD

**Issue by eliasvasylenko** [eclipse-efx/efxclipse-rt#241]
The widget for an MPart is created as follows:

```
    @Override
    protected Pane createWidget() {
      Pane tmp = CustomContainerSupport.createContainerPane(this.logger, this.context);
      final Pane p = tmp == null ? new BorderPane() : tmp;

      p.addEventFilter(MouseEvent.MOUSE_PRESSED, new EventHandler<MouseEvent>() {

        @Override
        public void handle(MouseEvent event) {
          MPart domElement = getDomElement();
          if (domElement != null) {
            domElement.getContext().get(EPartService.class).activate(domElement, true);
            if (!checkFocusControl(getStaticLayoutNode()) && (domElement.getObject() != null)) {
              // ContextInjectionFactory.invoke(domElement.getObject(),
              // Focus.class, domElement.getContext(), null);
              // if (!checkFocusControl()) {
              // p.requestFocus();
              // }
              p.requestFocus();
            }
          }
        }
      });
      return p;
    }
```

For parts which are added to the scene via placeholders `checkFocusControl` **always** returns `false`, as `getStaticLayoutNode().getScene()` returns `null` for the part.

This means that every click within the part fires spurious focus events. Components which check whether the user transfers focus away (e.g. to cancel modal editing) will do so when the user clicks within the component, which shouldn't happen.

I'd love to make a couple of PRs for this and the outstanding dnd issue #173 but I'm struggling to get my head around the placeholder renderer.

**Comment by eliasvasylenko** [comment]
Okay well this appears to be fixed easily enough by changing the line

        getWidget().getChildren().setAll((Node) contentWidget.getWidgetNode());

to

        getWidget().getChildren().setAll((Node) contentWidget.getStaticLayoutNode());

in `DefPlaceholderRenderer`, but I have no idea if that breaks anything else (it seems okay in my application) because I don't really know what the purpose of the "static layout node" is...

**Comment by tomsontom** [comment]
i need to take a look myself ;-)

**Comment by tomsontom** [comment]
hm i don't think this is will work the idea with the static-node is that that one stays in the original position (keeping the slot free in the parent layout) whereas the child is moved (same happens when you min/max)

**Comment by eliasvasylenko** [comment]
Okay, so then if I understand the situation correctly, the problem is that the `staticLayoutNode` for parts in the `sharedElements` list is not valid (or rather, it deliberately refers to an area off-screen), so this doesn't work for them when they're referred to by a placeholder.

So then is there a reason why we pass the `staticLayoutNode()` to `checkFocusControl` instead of just passing the `widgetNode()`? Is it to avoid unnecessary instantiation of the widget node in certain circumstances? Producing the correct results I think is better than producing the wrong results a bit more quickly! Or maybe there's something else I'm missing?

**Comment by tomsontom** [comment]
I'm sorry that it took so long to fix this - a customer filed an internal issue with a totally different problem (placeholder-parts did not show up in MPartStack initially).

This will be fixed in the up-coming release end of the month
