### ISSUE TITLE
Short-circuit PartRenderingEngine.createGui() when isToBeRendered() is set to false during initialization

### ISSUE THREAD

**Issue by eliasvasylenko** [eclipse-efx/efxclipse-rt#248]
For certain MPart instances I hook into the `TOPIC_CONTEXT` and `TOPIC_WIDGET` events to prepare the context during initialization. This mostly works great, but sometimes I want to conditionally set the part to not be rendered in response to these events, as the context can't be properly configured. Unfortunately setting toBeRendered to false at this point does not prevent the contribution object from being created and injected and so I have to deal with the extra error handling only for the contribution object to be immediately disposed.

Currently `PartRenderingEngine.createGui` checks if `element.isToBeRendered` is false and if so returns *before* creating the context and widget, but this is the last time it checks. In my case this value can change after the context and widget have been created so I'd like for it to re-check at these points. I intend to make a PR with these changes.

**Comment by tomsontom** [comment]
sounds ok
