### ISSUE TITLE
Closing a dirty part does not remove it from the application model therefore handlers checking for dirty have wrong state

### ISSUE THREAD

**Issue by vogella** [eclipse-efx/efxclipse-rt#275]
I have a part which is dirty. User clicks the close button and it is closed after confirmation with the user. A handler which checks for dirty remains active.

Checking the application model shows that the closed part is still part of the application model, which is unexpected.

To test: define handler simlar to the following. Make a part dirty and close it.

````
 
package testapp.app.handler;

import org.eclipse.e4.core.di.annotations.CanExecute;
import org.eclipse.e4.core.di.annotations.Execute;
import org.eclipse.e4.ui.workbench.modeling.EPartService;

public class TestHandler {
	@Execute
	public void execute() {
		System.out.println("Test handler");
	}
	
	@CanExecute
	public boolean canExecute(EPartService partService) {
		System.out.println(partService.getParts().size());
		System.out.println(partService.getDirtyParts().isEmpty());
		return (!partService.getDirtyParts().isEmpty());
	}
		
}
````

**Comment by tomsontom** [comment]
Yes this is expected and also done that way in SWT. A Part is only removed from the application model if you tagged to get removed, otherwise it is just set to `tbr=false`

**Comment by vogella** [comment]
IIRC correctly the SWT renderer removes parts without any additional tag. I will test and report back.

**Comment by tomsontom** [comment]
if it does you've just discovered a severe bug in e4-swt ;-)

**Comment by vogella** [comment]
Thanks Tom, indeed the SWT renderer behaves similar. "removeOnHide" must be used.
