### ISSUE TITLE
Position focus on first focusable node if no @Focus annotation is present

### ISSUE THREAD

**Issue by ckeimel** [eclipse-efx/efxclipse-rt#281]
If a part is made visible, as a user, I would usualy like to have the focus on the first focusable element so I can start working using the key board right away.   In this sample that would be the "TextField" next to "Input 1":
![2019-01-07_140354](https://user-images.githubusercontent.com/2076725/50831801-5b32aa00-134c-11e9-8384-de45ed80fc9e.png)

Using e4 this can currently only be achieved be using the @Focus annotation in the part. If the annotation is not present the focus will be set on the BorderPane and is therefor not visible. This is very prominent right after the start of an application which will look like this:
![2019-01-07_140430](https://user-images.githubusercontent.com/2076725/50831878-a3ea6300-134c-11e9-8166-cb0819b23157.png)

As a developer I would like to change the default behaviour: If no @Focus annotation is present the focus should automatically be set to the first focusable element.

I do not think we need a flag to enable/disable this, as:
* a user would want this anyway, why hide the focus?
* this is the way a native JavaFX application behaves

**Comment by tomsontom** [comment]
The code where to fix this is https://github.com/eclipse-efx/efxclipse-rt/blob/cec5f7973c73edd1442e48fe68aca427ba66cc4f/modules/ui/org.eclipse.fx.ui.workbench.renderers.fx/src/main/java/org/eclipse/fx/ui/workbench/renderers/fx/DefPartRenderer.java#L78
