### ISSUE TITLE
KeyBindings do not support the Platform tag

### ISSUE THREAD

**Issue by CamilleLetavernier** [eclipse-efx/efxclipse-rt#283]
The E4 Application model allows to define a "platform" tag on KeyBindings, to provide platform-specific bindings. However, this is not supported in efx: the tag is parsed and added to the map of Attributes, but then it is ignored in org.eclipse.fx.ui.keybindings.e4.internal.BindingServiceImpl

Some other tags (e.g. Locale) are unsupported as well

**Comment by tomsontom** [comment]
We should file an upstream ticket to request support in the editor for those tags?
