### ISSUE TITLE
Migrate the SWT E4 Spy Tools to JavaFX

### ISSUE THREAD

**Issue by lauritziu** [eclipse-efx/efxclipse-rt#287]
To support the development of a E4 application some very useful tools exist helping to investigate the current state of a running E4 application. To get an impression of the tools see the following video.

The following tools exists:

Model Spy (investigate the current application model)
Context Spy (provides a deep insight into the context hierarchy with search support)
Preferences Spy (shows available preferences and changes to it)
Event Spy (observes all the Eclipse events fired and allows to filter the events)
These tools are great but they are all written in SWT and therefore not easily usable in a JavaFx Eclipse application.

It would be great to migrate the tools to JavaFX and provide them with the efxclipse tooling.

**Comment by lauritziu** [comment]
We have already migrated the following tools:

Context Spy
Preferences Spy
Event Spy
We would like to contribute the three. This issue is mainly to document that these tools are already available and duplicate work can be avoided.

We would need to change the package names to at.bestsolution but then we can create an pullrequest. @tomsontom any further requirements that would it be easier to accept the pullrequest?

**Comment by tomsontom** [comment]
* So first of all - the current work happens in the 3.x branch
* I think those tools should go to `modules/tool/`
* The bundle prefix should be `org.eclipse.fx.tool`

I would prefer single PR for each Spy - we might have to file CQs but that depends on the contribution size (LOC)

**Comment by tomsontom** [comment]
Perfect! Amazing contribution!

**Comment by lauritziu** [comment]
Thanks 🙂

**Comment by ckeimel** [comment]
@lauritziu awesome! thanks for this!!
