### ISSUE TITLE
[Local development] Changes to the OSGi Integration fragment are not reflected in the build

### ISSUE THREAD

**Issue by TobiasAsk** [eclipse-efx/efxclipse-rt#293]
I have cloned the repo in an attempt to figure out #292. I build the project (`mvn clean verify` in `releng\org.eclipse.fx.releng`) after making changes to `FXClassLoader`, and I add the locally built update site (`releng\org.eclipse.fx.updatesite\target\site_assembly.zip`) to the target definition of the plug-in I'm working on. The version of the `Minimal JavaFX OSGi integration bundles` plug-in is not the locally built one, however, but rather one fetched from the nightly build site. I can see from the POM that the `org.eclipse.fx.osgi` module is not a child of the root releng project, so this should perhaps be expected.

I have, however, also tried building the `shared.releng` project and including the `Minimal JavaFX OSGi integration bundles` plug-in from the (locally built) shared update site instead of the main one in my target definition. This does not work either. It is very odd, as I can confirm that the included version of the `org.eclipse.fx.osgi` plug-in is the locally built one:

![target](https://user-images.githubusercontent.com/10739403/51472690-7ead1a00-1d7a-11e9-8345-51436e642802.PNG)

During debugging, however, the lines added to `FXClassLoader` are simply skipped, even though they can be seen in the editor. I can confirm that the `org.eclipse.fx.osgi` JAR found by Eclipse is the locally built one. Am I missing something?

**Comment by tomsontom** [comment]
the best option to debug this problem is to launch with an inner eclipse. For that to work you need to import _org.eclipse.osgi_ , then move it**physically** next to the _org.eclipse.fx.osgi_ folder and reimport _org.eclipse.osgi_ and then in start with those 2 bundles in your launch configuration
