### ISSUE TITLE
How to get text of current paragraph of caretposition of StyledTextArea?

### ISSUE THREAD

**Issue by krstn420** [eclipse-efx/efxclipse-rt#299]
`This text is not selected because cursor is in next text block

Start point of selected text ....
Because cursor is here | .....
Line 2 could also contain spaces/tabs
Rest of text also selected

This text is not selected ...`

I want to either select or rather get the text (boundaries), is there an easy comfortable way to do this with the current implementation of StyledTextArea?

**Comment by tomsontom** [comment]
@redrezo do you maybe know that?
