### ISSUE TITLE
JPMS: package exported but not opened

### ISSUE THREAD

**Issue by TobiasAsk** [eclipse-efx/efxclipse-rt#313]
Scene Builder needs to use an FXMLLoader with its static load flag set to false. This has to be done using reflection, as it is not public API, but after the modularisation of JavaFX it is no longer possible. An error saying that the javafx.fxml module does not open the fxml package is produced. To fix this I attempt to add the `-Defxclipse.osgi.hook.add-opens="javafx.fxml/javafx.fxml=ALL-UNNAMED"` argument to the VM, but it doesn't help. Debugging shows a surprising result. The `ModuleLayerWrapper.ControllerWrapper` that is returned by `ModuleLayerWrapper.ControllerWrapper.addOpens` contains the following:

![controller_contents](https://user-images.githubusercontent.com/10739403/53017394-24be7380-3450-11e9-9ec0-d18eb1ba239e.png)

Notice that, while the `javafx.fxml` package is added to the map of exported packages, it is _not_ added to the map of open packages. I see that `ModuleLayerWrapper.ControllerWrapper.addOpens` invokes the correct `addOpens` method, so what is going on here?

**Comment by tomsontom** [comment]
Guess what each OSGi-Module is in its own Unnamed-Module. Yes there are multiple of them! I need to check the sources how you can do that for with the command line parameters

**Comment by TobiasAsk** [comment]
Any updates on this front?

**Comment by tomsontom** [comment]
I hope i can find some time this week to look into this. Is there a way for me to debug your problem to find a solution for your UC?

**Comment by TobiasAsk** [comment]
Great! You can create an `FXMLLoader` and use reflection on it:
```java
FXMLLoader loader = new FXMLLoader();
Clazz<?> clazz = loader.getClass();
Method setStaticLoadMethod = clazz.getDeclaredMethod("setStaticLoad", boolean.class);
setStaicLoadMethod.setAccessible(true);
```
This crashes due to a `java.lang.reflect.InaccessibleObjectException: Unable to make void javafx.fxml.FXMLLoader.setStaticLoad(boolean) accessible: module javafx.fxml does not "opens javafx.fxml" to unnamed module @4928a347`.

**Comment by tomsontom** [comment]
so the problem is that to allow setAccessible(true) the package needs to opend to the calling module see #332 how i did it for my bundle. I guess you need to do the same for the SceneBuilder bundles you wrapped as OSGi-Modules.
