### ISSUE TITLE
Unable to use JavaFX bundles from the p2 repo

### ISSUE THREAD

**Issue by TobiasAsk** [eclipse-efx/efxclipse-rt#323]
I am unable to use the bundles located at [the p2 repo](http://downloads.efxclipse.bestsolution.at/p2-repos/openjfx-11/repository/) to include JavaFX in my plug-in. When added to the target platform, they make no difference. In order for JavaFX to be loaded, I have to use my local SDK with the `-Defxclipse.java-modules.dir=PATH_TO_JAVAFX_SDK` argument instead. The bundle manifests are quite minimal:

![manifest](https://user-images.githubusercontent.com/10739403/53811586-0b421f00-3f5a-11e9-9e29-205800ec8161.PNG)

Shouldn't the bundles export the JavaFX packages in order for other plug-ins to be able to consume them?

**Comment by tomsontom** [comment]
no - those are pure deployment artifacts - at runtime we spin up a layer with them
