### ISSUE TITLE
Changing element's containerData at runtime doesn't impact size

### ISSUE THREAD

**Issue by TyPh00nCdr** [eclipse-efx/efxclipse-rt#330]
Manipulation of an existing, rendered `MPartStack`'s `containerData` (manually or by calling [`EModelService#insert`](https://help.eclipse.org/2018-12/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/e4/ui/workbench/modeling/EModelService.html#insert-org.eclipse.e4.ui.model.application.ui.basic.MPartSashContainerElement-org.eclipse.e4.ui.model.application.ui.basic.MPartSashContainerElement-int-float-)) doesn't change the `MPartStack`'s size (i.e. `weight`) in the rendered UI. 

The [`PartRenderingEngine#createGui(MUIElement, Object, IEclipseContext)`](https://github.com/eclipse-efx/efxclipse-rt/blob/cfdb23a65333a59524db1b1a198a3344308418fe/modules/ui/org.eclipse.fx.ui.workbench.fx/src/main/java/org/eclipse/fx/ui/workbench/fx/PartRenderingEngine.java#L234) method just returns the element's widget if it exists without checking for a change in the `containerData`. Hence, the widget's `weight` is never adjusted to the new `containerData` value.

As a result, when inserting a new `MPartStack` by e.g. calling [`EModelService#insert`](https://help.eclipse.org/2018-12/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/e4/ui/workbench/modeling/EModelService.html#insert-org.eclipse.e4.ui.model.application.ui.basic.MPartSashContainerElement-org.eclipse.e4.ui.model.application.ui.basic.MPartSashContainerElement-int-float-), the new element will always take up the majority of the space instead of the specified `ratio`-argument.

**Comment by TyPh00nCdr** [comment]
This seems to have been an error in v.3.5.0. At least [EModelService#insert](https://help.eclipse.org/2018-12/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/e4/ui/workbench/modeling/EModelService.html#insert-org.eclipse.e4.ui.model.application.ui.basic.MPartSashContainerElement-org.eclipse.e4.ui.model.application.ui.basic.MPartSashContainerElement-int-float-) works as intended in v.3.6.0. 

I will update this issue if I can somehow reproduce the bug in v.3.6.0 as well.

**Comment by tomsontom** [comment]
Might be fixed with: https://github.com/eclipse-efx/efxclipse-rt/commit/5f708417852d5059ca79639c30530be4f2e2bcf2 - beside that I would advice to use the compat-sashes (by launch with vmarg -Defxclipse.eclipse.compat.sash=true) to get proper resize behavior

**Comment by TyPh00nCdr** [comment]
How do the `Sash` implementations differ from each other and what advantage does the compatibility sash have over the regular one, now that I don't have the bug any longer? (To what is it supposed to be compatible? I suppose it's a SWTonFX-compatibility implementation, since that's the only documentation I could find regarding e(fx)clipse compatibility modes.)

**Comment by TyPh00nCdr** [comment]
Still wondering about the implementation details of the different `Sash`es since there seems to be virtually no difference whether or not I launch with the compatibility sash VM-arg.

**Comment by tomsontom** [comment]
They behave differently when you eg resize, ... .
