### ISSUE TITLE
[Performances] Add Util methods to attach a Sub-graph to a Scene

### ISSUE THREAD

**Issue by CamilleLetavernier** [eclipse-efx/efxclipse-rt#340]
Some versions of JavaFX have poor performances when attaching a large subgraph to a Scene:

https://bugs.openjdk.java.net/browse/JDK-8151756
https://bugs.openjdk.java.net/browse/JDK-8193445

E(fx)clipse should provide a Util method to attach a subgraph to a Scene, containing a workaround for this performance issue

**Comment by ckeimel** [comment]
Adding information from pull request [1] to this ticket:

* Add some methods to org.eclipse.fx.ui.controls.Util containing a performances workaround for attaching nodes to a Scene
* The workaround will only be applied when -Defxclipse.optimize.attach=true is passed to the Application

[1]: https://github.com/eclipse-efx/efxclipse-rt/pull/341
