### ISSUE TITLE
JavaFXCompatUtil calls non-existent "setPosition" instead of "setCaretPosition" via reflection

### ISSUE THREAD

**Issue by hoelzl-florian** [eclipse-efx/efxclipse-rt#352]
As it says in the subject, here is what worked for me in "JavaFXCompatUtil#setCaretPosition(Text, int)"
method (line 157ff.):
Method m = Text.class.getDeclaredMethod("setCaretPosition", int.class); //$NON-NLS-1$

Three lines later should also be corrected:
"Unable to call Text#setCaretPosition()"

**Comment by tomsontom** [comment]
Thanks for the report - to get more credit for finding and fixing think about providing a PR!
