### ISSUE TITLE
--add-opens in an efxclipse application

### ISSUE THREAD

**Issue by SimonScholz** [eclipse-efx/efxclipse-rt#353]
In a customers code base ControlsFx is being used and unfortunately it makes heavy use of internal JavaFx API, which lead to exceptions like this:
`Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public static com.sun.javafx.css.StyleManager com.sun.javafx.css.StyleManager.getInstance() accessible: module javafx.graphics does not "exports com.sun.javafx.css" to unnamed module @39e3ad0f`

Also see: https://github.com/controlsfx/controlsfx/issues/1100

In this issue they suggest to use the --add-opens vm argument to simply make this internal API accessible.

When I add `--add-opens=javafx.graphics/com.sun.javafx.css=ALL-UNNAMED` to the vm args I get the following warnings:

> WARNING: Unknown module: javafx.graphics specified to --add-opens

And when using `-Defxclipse.osgi.hook.add-opens="javafx.graphics/com.sun.javafx.css=ALL-UNNAMED"` I do not get any warning, but this also does not work for my project and I still get the InaccessibleObjectException from above.

Can you tell me how to properly open certain modules using efxclipse, Java11 and OpenJFX11?
I followed this guide: https://github.com/eclipse-efx/efxclipse-eclipse/wiki/Eclipse4-application-on-OpenJFX-11

Everything else works pretty good with the setup from the guide except of the ControlsFx controls, which cause the InaccessibleObjectException.

Looking forward to find a solution to open certain modules.

**Comment by tomsontom** [comment]
As we are booting an extra JPMS-Layer to install the OpenJFX modules command line switches don't really help you. What you need to provide the system are hints inside the MANIFEST.MF.

If you eg look at https://github.com/eclipse-efx/efxclipse-rt/blob/f6ed33c887c81a359bf0ffc3ac82d175a99da370/modules/ui/org.eclipse.fx.ui.workbench.fx/META-INF/MANIFEST.MF#L62 you see how an OSGi-Module can grant itself access to internal APIs.

The question what you put in your MANIFEST is how you ship controls-fx:
* do you repackage or even wrap in your own module
* is it an own OSGi-Module provided from external

For UC-1 just follow what efxclipse does for its own bundles. For UC-2 you should be able to cross patch by putting a header like this in one of your root modules MANIFEST.MF.

```
Java-Module-AddExports: javafx.graphics/com.sun.javafx.application=BUNDLE(org.controlsfx@1.0.0),javafx.graphics/com.sun.glass.ui=BUNDLE(org.controlsfx@1.0.0)
```
and replace `org.controlsfx` and `1.0.0`  through the real bundle symbolic name and its version. In case this does not work you need to start debugging - https://github.com/eclipse-efx/efxclipse-rt/blob/3.x/modules/core/org.eclipse.fx.osgi/src/main/java/org/eclipse/fx/osgi/fxloader/jpms/JavaModuleLayerModification.java

BTW: nice side story. It does not help to export something to ALL-UNNAMED because each classloader == each single OSGi-Bundle is in its own unnamed module ;-)

**Comment by SimonScholz** [comment]
Thanks a lot @tomsontom 

UC-1 is the case, I am wrapping ControlsFx by using the bnd-platform Gradle plugin: https://github.com/stempler/bnd-platform

I simply added all "--add-opens" mentioned in the ControlsFx issue concerning Java 11 (https://github.com/controlsfx/controlsfx/issues/1100) and had quite some success when using your advice.
The generated MANIFEST.MF file looks like this:

```
Manifest-Version: 1.0
Bnd-LastModified: 1555429926569
Bundle-Description: High quality UI controls and other tools to comple
 ment the core JavaFX distribution
Bundle-ManifestVersion: 2
Bundle-Name: ControlsFX
Bundle-SymbolicName: org.controlsfx
Bundle-Version: 11.0.0
Export-Package: org.controlsfx.control;uses:="javafx.beans.property,ja
 vafx.beans.value,javafx.collections,javafx.concurrent,javafx.css,java
 fx.event,javafx.geometry,javafx.scene,javafx.scene.control,javafx.sce
 ne.image,javafx.scene.input,javafx.scene.layout,javafx.scene.paint,ja
 vafx.scene.shape,javafx.stage,javafx.util,org.controlsfx.control.acti
 on,org.controlsfx.property.editor",org.controlsfx.control.action;uses
 :="javafx.beans,javafx.beans.property,javafx.collections,javafx.event
 ,javafx.scene,javafx.scene.control,javafx.scene.input,org.controlsfx.
 control",org.controlsfx.control.cell;uses:="javafx.scene.image,javafx
 .scene.media,javafx.scene.paint,org.controlsfx.control",org.controlsf
 x.control.decoration;uses:="javafx.collections,javafx.geometry,javafx
 .scene",org.controlsfx.control.table;uses:="javafx.beans.property,jav
 afx.collections,javafx.collections.transformation,javafx.scene,javafx
 .scene.control,javafx.scene.layout,javafx.util",org.controlsfx.contro
 l.table.model,org.controlsfx.control.textfield;uses:="javafx.beans.pr
 operty,javafx.event,javafx.scene,javafx.scene.control,javafx.util",or
 g.controlsfx.dialog;uses:="javafx.beans.property,javafx.collections,j
 avafx.concurrent,javafx.scene,javafx.scene.control,javafx.scene.text,
 javafx.util",org.controlsfx.glyphfont;uses:="javafx.beans.property,ja
 vafx.scene.control,javafx.scene.paint,org.controlsfx.tools",org.contr
 olsfx.property;uses:="javafx.beans.value,javafx.collections,org.contr
 olsfx.control,org.controlsfx.property.editor",org.controlsfx.property
 .editor;uses:="javafx.beans.value,javafx.scene,javafx.util,org.contro
 lsfx.control",org.controlsfx.tools;uses:="javafx.beans.value,javafx.s
 cene,javafx.scene.control,javafx.scene.layout,javafx.scene.paint,java
 fx.stage,javafx.util",org.controlsfx.validation;uses:="javafx.beans.p
 roperty,javafx.scene.control,org.controlsfx.validation.decoration",or
 g.controlsfx.validation.decoration;uses:="javafx.scene,javafx.scene.c
 ontrol,org.controlsfx.control.decoration,org.controlsfx.validation"
Implementation-Title: ControlsFX
Implementation-Version: 11.0.0
Import-Package: javax.inject;version="1.0.0"
Java-Module-AddExports: javafx.graphics/javafx.scene=.,javafx.graphics
 /javafx.css=.,javafx.controls/javafx.scene.control=.,javafx.base/java
 fx.event=.,javafx.base/javafx.collections=.,javafx.graphics/javafx.cs
 s=.,javafx.graphics/com.sun.javafx.scene=.,javafx.graphics/javafx.sce
 ne=.,javafx.graphics/com.sun.javafx.scene.traversal=.,javafx.graphics
 /com.sun.javafx.css=.,javafx.controls/com.sun.javafx.scene.control.be
 havior=.,javafx.controls/com.sun.javafx.scene.control=.,javafx.contro
 ls/com.sun.javafx.scene.control.inputmap=.,javafx.base/com.sun.javafx
 .event=.,javafx.base/com.sun.javafx.collections=.,javafx.base/com.sun
 .javafx.runtime=.,javafx.graphics/com.sun.javafx.css=.,javafx.graphic
 s/com.sun.javafx.application=.,javafx.graphics/com.sun.glass.ui=.
Originally-Created-By: 11 (Oracle Corporation)
Private-Package: impl.org.controlsfx,impl.org.controlsfx.autocompletio
 n,impl.org.controlsfx.behavior,impl.org.controlsfx.collections,impl.o
 rg.controlsfx.control.validation,impl.org.controlsfx.i18n,impl.org.co
 ntrolsfx.skin,impl.org.controlsfx.table,impl.org.controlsfx.tools,imp
 l.org.controlsfx.tools.rectangle,impl.org.controlsfx.tools.rectangle.
 change,impl.org.controlsfx.version,impl.org.controlsfx.worldmap,org.c
 ontrolsfx.control.spreadsheet
Require-Capability: osgi.ee;filter="(&(osgi.ee=JavaSE)(version=11))"
Specification-Title: Java Version 9
Specification-Version: 11.0.0
Tool: Bnd-3.4.0.201707252008
```

Unfortunately I still get some errors, because ControlsFx uses reflection to get the children of a certain Parent:

```
java.lang.reflect.InaccessibleObjectException: Unable to make protected javafx.collections.ObservableList javafx.scene.Parent.getChildren() accessible: module javafx.graphics does not "opens javafx.scene" to unnamed module @555cf22
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
	at impl.org.controlsfx.ImplUtils.getChildrenReflectively(ImplUtils.java:148)
	at impl.org.controlsfx.ImplUtils.getChildren(ImplUtils.java:125)
	at org.controlsfx.control.decoration.GraphicDecoration.applyDecoration(GraphicDecoration.java:115)
	at impl.org.controlsfx.skin.DecorationPane.showDecoration(DecorationPane.java:74)
	at impl.org.controlsfx.skin.DecorationPane.addAllDecorationsOnNode(DecorationPane.java:119)
	at impl.org.controlsfx.skin.DecorationPane.updateDecorationsOnNode(DecorationPane.java:70)
	at org.controlsfx.control.decoration.Decorator.lambda$updateDecorationsOnNode$0(Decorator.java:165)
	at org.controlsfx.control.decoration.Decorator.lambda$getDecorationPane$1(Decorator.java:204)
	at org.controlsfx.control.decoration.Decorator$1.invalidated(Decorator.java:222)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:348)
```

It seems that this method is causing the problem:

https://github.com/controlsfx/controlsfx/blob/e642661658bd8ea76950bdfd7d48e64ee0968360/controlsfx/src/main/java/impl/org/controlsfx/ImplUtils.java#L140

Do you have any idea how ControlsFx can be fixed to make it work or any other idea to solve this problem?

**Comment by tomsontom** [comment]
see #332 beside the AddExport you also need AddOpens because to call setAccessible(true) on private/package methods the package needs to be exported to the calling module

**Comment by domenicquirl** [comment]
I have also been trying to get controlsfx to work, sadly a lot of the export restrictions still seem to persist as of Version 11.2.2. I'm having trouble following the solution suggested here in an OSGI context with dynamic loading: I am able to export the base `javafx` modules when `javafx` initializes, but everything else is only loaded later and not available at that point (the corresponding errors are `JavaModuleLayerModification#applyConfigurations - Source module ' javafx.controls' is not dynamically loaded. Could not export 'com.sun.javafx.scene.control.behavior'.` and similar).

As far as I can tell, the export is not re-attempted later when the remaining `javafx` classes are activated. Do you have any advice on how to set up exports/opens in such a way that they apply to all necessary `javafx` components? Or, alternatively, force the exported modules to be available on startup?
