### ISSUE TITLE
Switch to EPL 2.0

### ISSUE THREAD

**Issue by tomsontom** [eclipse-efx/efxclipse-rt#416]

**Comment by waynebeaton** [comment]
Please be sure to add LICENSE and CONTRIBUTING files to the repository root. I also noticed that at least some files do not have the required copyright and license headers. The [Documentation Generator](https://www.eclipse.org/projects/tools/documentation.php?id=technology.efxclipse) provides templates for these based on project metadata.

Here's an [EPL-2.0 example header](https://www.eclipse.org/projects/tools/legal/header.php?licenses=EPL-2.0).
